---
abstract: 'lightweight web application framework'
author:
  - 'Tokuhiro Matsuno'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Amon2
name: Amon2
no_index:
  directory:
    - eg
    - inc
    - t
    - xt
recommends:
  Test::WWW::Mechanize::PSGI: 0
requires:
  Data::OptList: 0.106
  Data::Section::Simple: 0
  Exporter: 5.64
  HTML::FillInForm::Lite: 1.09
  HTTP::Date: 6
  HTTP::Session: 0.41
  HTTP::Status: 6.00
  JSON: 2
  MRO::Compat: 0
  Module::Find: 0.1
  Plack: 0.9982
  Plack::Middleware::ReverseProxy: 0
  Router::Simple: 0.06
  Router::Simple::Sinatraish: 0.02
  Test::More: 0.98
  Text::Xslate: 1.4001
  Text::Xslate::Bridge::TT2Like: 0.00008
  Try::Tiny: 0.06
  URI: 1.54
  URI::Escape: 3.3
  parent: 0.223
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tokuhirom/Amon.git
version: 2.54
