---
abstract: 'lightweight web application framework'
author:
  - 'Tokuhiro Matsuno'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.98
  Test::Requires: 0.06
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Amon2
name: Amon2
no_index:
  directory:
    - eg
    - inc
    - t
    - xt
requires:
  Exporter: 0
  Plack: 0.9982
  Plack::Session: 0
  Router::Simple: 0.06
  Router::Simple::Sinatraish: 0.02
  Text::Xslate: 1.5006
  Try::Tiny: 0.06
  URI: 1.54
  parent: 0.223
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tokuhirom/Amon.git
version: 3.51
