---
abstract: 'lightweight web application framework'
author:
  - 'Tokuhiro Matsuno'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Amon2
name: Amon2
no_index:
  directory:
    - eg
    - inc
    - t
    - xt
requires:
  Data::OptList: 0.106
  Data::Section::Simple: 0.03
  Exporter: 5.64
  File::Copy::Recursive: 0.38
  HTTP::Date: 6.00
  MRO::Compat: 0.11
  Module::Find: 0.10
  Plack: 0.9982
  Plack::Session: 0
  Router::Simple: 0.06
  Router::Simple::Sinatraish: 0.02
  Test::More: 0.98
  Text::Xslate: 1.4001
  Text::Xslate::Bridge::TT2Like: 0.00010
  Try::Tiny: 0.06
  URI: 1.54
  URI::Escape: 3.3
  parent: 0.223
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tokuhirom/Amon.git
version: 3.06
