---
abstract: 'lightweight web application framework'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0.06
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Amon2
no_index:
  directory:
    - eg
    - inc
    - t
    - xt
provides:
  Amon2:
    file: lib/Amon2.pm
    version: 3.70
  Amon2::Config::Simple:
    file: lib/Amon2/Config/Simple.pm
    version: 0
  Amon2::Declare:
    file: lib/Amon2/Declare.pm
    version: 0
  Amon2::Plugin::Web::CSRFDefender:
    file: lib/Amon2/Plugin/Web/CSRFDefender.pm
    version: 0
  Amon2::Plugin::Web::FillInFormLite:
    file: lib/Amon2/Plugin/Web/FillInFormLite.pm
    version: 0
  Amon2::Plugin::Web::HTTPSession:
    file: lib/Amon2/Plugin/Web/HTTPSession.pm
    version: 0
  Amon2::Plugin::Web::JSON:
    file: lib/Amon2/Plugin/Web/JSON.pm
    version: 0
  Amon2::Plugin::Web::NoCache:
    file: lib/Amon2/Plugin/Web/NoCache.pm
    version: 0
  Amon2::Plugin::Web::PlackSession:
    file: lib/Amon2/Plugin/Web/PlackSession.pm
    version: 0
  Amon2::Plugin::Web::Streaming:
    file: lib/Amon2/Plugin/Web/Streaming.pm
    version: 0
  Amon2::Plugin::Web::Streaming::Writer:
    file: lib/Amon2/Plugin/Web/Streaming.pm
    version: 0
  Amon2::Plugin::Web::WebSocket:
    file: lib/Amon2/Plugin/Web/WebSocket.pm
    version: 0
  Amon2::Setup::Asset::Blueprint:
    file: lib/Amon2/Setup/Asset/Blueprint.pm
    version: 0
  Amon2::Setup::Asset::Bootstrap:
    file: lib/Amon2/Setup/Asset/Bootstrap.pm
    version: 0
  Amon2::Setup::Asset::ES5Shim:
    file: lib/Amon2/Setup/Asset/ES5Shim.pm
    version: 0
  Amon2::Setup::Asset::MicroDispatcherJS:
    file: lib/Amon2/Setup/Asset/MicroDispatcherJS.pm
    version: 0
  Amon2::Setup::Asset::MicroLocationJS:
    file: lib/Amon2/Setup/Asset/MicroLocationJS.pm
    version: 0
  Amon2::Setup::Asset::MicroTemplateJS:
    file: lib/Amon2/Setup/Asset/MicroTemplateJS.pm
    version: 0
  Amon2::Setup::Asset::SprintfJS:
    file: lib/Amon2/Setup/Asset/SprintfJS.pm
    version: 0
  Amon2::Setup::Asset::StrftimeJS:
    file: lib/Amon2/Setup/Asset/StrftimeJS.pm
    version: 0
  Amon2::Setup::Asset::jQuery:
    file: lib/Amon2/Setup/Asset/jQuery.pm
    version: 0
  Amon2::Setup::Flavor:
    file: lib/Amon2/Setup/Flavor.pm
    version: 0
  Amon2::Setup::Flavor::Basic:
    file: lib/Amon2/Setup/Flavor/Basic.pm
    version: 0.01
  Amon2::Setup::Flavor::Large:
    file: lib/Amon2/Setup/Flavor/Large.pm
    version: 0
  Amon2::Setup::Flavor::Minimum:
    file: lib/Amon2/Setup/Flavor/Minimum.pm
    version: 0.01
  Amon2::Setup::VC::Git:
    file: lib/Amon2/Setup/VC/Git.pm
    version: 0
  Amon2::Trigger:
    file: lib/Amon2/Trigger.pm
    version: 0
  Amon2::Util:
    file: lib/Amon2/Util.pm
    version: 0
  Amon2::Web:
    file: lib/Amon2/Web.pm
    version: 0
  Amon2::Web::Dispatcher::Lite:
    file: lib/Amon2/Web/Dispatcher/Lite.pm
    version: 0
  Amon2::Web::Dispatcher::RouterSimple:
    file: lib/Amon2/Web/Dispatcher/RouterSimple.pm
    version: 0
  Amon2::Web::Request:
    file: lib/Amon2/Web/Request.pm
    version: 0
  Amon2::Web::Response:
    file: lib/Amon2/Web/Response.pm
    version: 0
  Amon2::Web::Response::Callback:
    file: lib/Amon2/Web/Response/Callback.pm
    version: 0
  Amon2::Web::WebSocket:
    file: lib/Amon2/Web/WebSocket.pm
    version: 0
requires:
  Exporter: 0
  Plack: 0.9982
  Plack::Session: 0
  Router::Simple: 0.14
  Router::Simple::Sinatraish: 0.02
  Text::Xslate: 1.6001
  Try::Tiny: 0.06
  URI: 1.54
  parent: 0.223
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 3.70
