---
abstract: 'lightweight web application framework'
author:
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0.06
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.6.3, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Amon2
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
requires:
  Encode: 0
  Exporter: 0
  File::Temp: 0
  Getopt::Long: 0
  HTML::FillInForm::Lite: 0
  HTTP::Headers: 0
  Hash::MultiValue: 0
  JSON: 2
  MRO::Compat: 0
  Plack: 0.9982
  Plack::Request: 0
  Plack::Response: 0
  Plack::Session: 0
  Plack::Util: 0
  Pod::Usage: 0
  Router::Simple: 0.14
  Router::Simple::Sinatraish: 0.02
  Scalar::Util: 0
  Text::Xslate: 1.6001
  Try::Tiny: 0.06
  URI: 1.54
  URI::Escape: 0
  URI::QueryParam: 0
  parent: 0.223
  perl: 5.008001
resources:
  bugtracker: https://github.com/tokuhirom/Amon/issues
  homepage: https://github.com/tokuhirom/Amon
  repository: git://github.com/tokuhirom/Amon.git
version: 3.99_01
x_contributors:
  - 'noblejasper <nobjas@gmail.com>'
  - 'noblejasper <jasper@main.noble-jasper.com>'
  - 'hiratara <hiratara@cpan.org>'
  - 's-aska <s.aska.org@gmail.com>'
  - 'Kentaro Kuribayashi <kentarok@gmail.com>'
  - 'Yuki Ibe <yibe@yibe.org>'
  - 'mattn <mattn.jp@gmail.com>'
  - 'Masahiro Nagano <kazeburo@gmail.com>'
  - 'rightgo09 <skyarrow09@gmail.com>'
  - 'karupanerura <karupa@cpan.org>'
  - 'hatyuki <hatyuki29@gmail.com>'
  - 'Keiji, Yoshimi <walf443@gmail.com>'
  - 'Nishibayashi Takuji <takuji31@gmail.com>'
  - 'dragon3 <ryuzo.yamamoto@gmail.com>'
  - 'Fuji, Goro <g.psy.va@gmail.com>'
  - 'issm <issmxx@gmail.com>'
  - 'hisaichi5518 <hisada.kazuki@gmail.com>'
  - 'Adrian <adrian@investometrica.com>'
  - 'Syohei YOSHIDA <syohex@gmail.com>'
  - 'Fuji, Goro <gfuji@cpan.org>'
